Add an entrypoint. Starting to add development tools.
wasmerio/wasm-python-api pull request #2
Opened 2019-11-23 17:55 UTC by Mec-iS

This PR tries to:
* add tests, examples, etc directories structure;
* add a `WebAssembly` function (see docstring) that allows an entrypoint to the ABC machinery by loading the Wasm binary;
* implement the first basic methods for `Module`.

Looking for feedback to start figuring out #1

2019-11-23 18:06 UTC, Mec-iS commented
one question for the `Instance` ABC.

We need to [instantiate from bytes](https://github.com/wasmerio/wasm-python-api/blob/master/webassembly/instance.py#L10)?

Once the module is created, can we instantiate from the existing module?

2019-11-28 14:13 UTC, Hywan requested changes
I think it's good to test the API with Wasmer. On the long-term, we should add more runtimes, to be sure it works for everyone. Good idea!

Can we run the examples as tests?

2019-11-28 14:13 UTC, Hywan commented on webassembly/instance.py
> +    # # Need to collect use cases for this class method, see PR#1
Why commenting this one?

2019-11-28 14:44 UTC, Mec-iS commented on webassembly/instance.py
> +    # # Need to collect use cases for this class method, see PR#1
yea I will roll this back as it should be possible to do something like:
```
istance = Instance.from_module(module)
``

2019-11-28 14:44 UTC, Mec-iS commented
> Can we run the examples as tests?
yes, only basic instantiation tests are there for now, but we will add examples and tests as I go on.

will aplly requested changed.

2019-12-02 11:53 UTC, Hywan commented
Can you push the source of `binaries/tests_binary.wasm` please (whatever it is)? Thanks!

2019-12-02 12:16 UTC, Mec-iS commented
@Hywan as far as I can see it is there -> https://github.com/wasmerio/wasm-python-api/pull/2/files#diff-f02d2e4081c7edba29c41b7f649c9516

it is the simple test case in `python-ext-wasm` btw

2025-08-31 16:54 UTC, closed without merging